spring:
  kafka:
    bootstrap-servers: home-nakazaway.com:9092
    template:
      default-topic: kafkaTest
    consumer:
      group-id: test
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: true
  firebase:
    credential: src/main/resources/config/kafkaConsumerAndFirebaseTest.json
    database: https://kafkatest-511d8.firebaseio.com